/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaGUI;

/**
 *
 * @author Client
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TFNilai = new javax.swing.JTextField();
        TFMapel = new javax.swing.JTextField();
        TFAbsen = new javax.swing.JTextField();
        TFNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel1.setText("Absen");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 120, 80, 30);

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel3.setText("Mata Pelajaran");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 160, 90, 30);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel4.setText("Nilai");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 200, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel5.setText("Nama");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 80, 80, 30);

        jLabel2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENILAIAN SISWA");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 20, 160, 40);
        getContentPane().add(TFNilai);
        TFNilai.setBounds(160, 200, 140, 30);
        getContentPane().add(TFMapel);
        TFMapel.setBounds(160, 160, 140, 30);
        getContentPane().add(TFAbsen);
        TFAbsen.setBounds(160, 120, 140, 30);
        getContentPane().add(TFNama);
        TFNama.setBounds(160, 80, 140, 30);

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 340, 160);

        btn1.setBackground(new java.awt.Color(255, 0, 0));
        btn1.setText("Proses");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(170, 280, 68, 25);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 550);

        setBounds(0, 0, 429, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling
        String nama = TFNama.getText();
        String absen = TFAbsen.getText();
        String mapel = TFMapel.getText();
        int nilai = Integer.parseInt(TFNilai.getText());
        
        //grade
        if ( nilai >= 101 ) {
            TextArea.setText("Nama : " +nama+"\n Absen : "+absen+ "\nMata pelajaran :"+mapel+"\n Nilai : "+nilai+"\n Keterangan : Amazing");
        } else if ( nilai == 100 ){
            TextArea.setText("Nama : " +nama+"\n Absen : "+absen+ "\nMata pelajaran :"+mapel+"\n Nilai : "+nilai+"\n Keterangan : Sempurna");
        } else if ( nilai >= 75 ){
            TextArea.setText("Nama : " +nama+"\n Absen : "+absen+ "\nMata pelajaran :"+mapel+"\n Nilai : "+nilai+"\n Keterangan : Lulus");
        } else {
           TextArea.setText("Nama : " +nama+"\n Absen : "+absen+ "\nMata pelajaran :"+mapel+"\n Nilai : "+nilai+"\n Keterangan : Tidak lulus");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFAbsen;
    private javax.swing.JTextField TFMapel;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFNilai;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
