/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lanjutan;

/**
 *
 * @author Client
 */
public class CekKesehatan extends javax.swing.JFrame {

    /**
     * Creates new form latihan3
     */
    public CekKesehatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submithitung = new javax.swing.JButton();
        submitulangi = new javax.swing.JButton();
        submitkeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Nama = new javax.swing.JTextField();
        Beratbadan = new javax.swing.JTextField();
        Tinggibadan = new javax.swing.JTextField();
        jbperempuan = new javax.swing.JRadioButton();
        jblaki = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idhasilanalisa = new javax.swing.JTextField();
        idsaran = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        beratideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CEK KESEHATAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 10, 170, 40);

        jLabel2.setText("Nama ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 60, 90, 30);

        submithitung.setText("Hitung");
        submithitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submithitungActionPerformed(evt);
            }
        });
        getContentPane().add(submithitung);
        submithitung.setBounds(110, 230, 100, 25);

        submitulangi.setText("Ulangi");
        submitulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitulangiActionPerformed(evt);
            }
        });
        getContentPane().add(submitulangi);
        submitulangi.setBounds(230, 230, 100, 25);

        submitkeluar.setText("Keluar");
        submitkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(submitkeluar);
        submitkeluar.setBounds(350, 230, 100, 25);

        jLabel10.setText("Hasil analisis kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 330, 160, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        jPanel1.add(Nama);
        Nama.setBounds(110, 10, 240, 30);

        Beratbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratbadanActionPerformed(evt);
            }
        });
        jPanel1.add(Beratbadan);
        Beratbadan.setBounds(110, 50, 240, 30);

        Tinggibadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggibadanActionPerformed(evt);
            }
        });
        jPanel1.add(Tinggibadan);
        Tinggibadan.setBounds(110, 90, 240, 30);

        bg.add(jbperempuan);
        jbperempuan.setText("Perempuan");
        jbperempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbperempuanActionPerformed(evt);
            }
        });
        jPanel1.add(jbperempuan);
        jbperempuan.setBounds(230, 130, 120, 23);

        bg.add(jblaki);
        jblaki.setText("Laki-Laki");
        jblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblakiActionPerformed(evt);
            }
        });
        jPanel1.add(jblaki);
        jblaki.setBounds(120, 130, 100, 23);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 130, 70, 20);

        jLabel4.setText("Tinggi badan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 90, 90, 30);

        jLabel3.setText("Berat badan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 100, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 100, 20, 15);

        jLabel6.setText("kg");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 50, 11, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 50, 390, 170);

        idhasilanalisa.setText("?");
        getContentPane().add(idhasilanalisa);
        idhasilanalisa.setBounds(50, 360, 400, 40);

        idsaran.setText("Saran?");
        getContentPane().add(idsaran);
        idsaran.setBounds(50, 410, 400, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 330, 440, 130);

        jPanel3.setBackground(new java.awt.Color(255, 204, 102));

        jLabel9.setText("kg");

        beratideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beratidealActionPerformed(evt);
            }
        });

        jLabel8.setText("Berat badan ideal anda adalah :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beratideal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beratideal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 270, 400, 30);

        setBounds(0, 0, 511, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void BeratbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BeratbadanActionPerformed

    private void TinggibadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggibadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggibadanActionPerformed

    private void jbperempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbperempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbperempuanActionPerformed

    private void jblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jblakiActionPerformed

    private void beratidealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beratidealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beratidealActionPerformed

    private void submitkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_submitkeluarActionPerformed

    private void submitulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitulangiActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Beratbadan.setText("");
        Tinggibadan.setText("");
        bg.clearSelection();
        idhasilanalisa.setText("");
        idsaran.setText("");
    }//GEN-LAST:event_submitulangiActionPerformed

    private void submithitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submithitungActionPerformed
        // TODO add your handling code here:
        double t, b, h = 0;
        
        //untuk mengambil nilai tinggi dan berat serta nama
        t = Double.valueOf(Tinggibadan.getText());
        b = Double.valueOf(Beratbadan.getText());
        String nm =  Nama.getText();
        
        //pilihan jenis kelamin
        if(jblaki.isSelected()){
           h = (t-100);
        }else if (jbperempuan.isSelected()){
            h = (t-104);
        }
        String temp = Double.toString(h);
        
        //logika untuk analisa hasil kesehatan
        if(h>b){
            beratideal.setText(temp);
            idhasilanalisa.setText("Maaf "+nm+" Anda kekurangan berat badan");
            idsaran.setText("Makan yang banyak dan bergizi");
        }else if (h>b){
            beratideal.setText(temp);
            idhasilanalisa.setText("Maaf "+nm+" Anda kelebihan berat badan");
            idsaran.setText("Kurangi makan dan makan-makanan bergizi");
        }else {
            beratideal.setText(temp);
            idhasilanalisa.setText("Selamat " + nm + " berat  badan anda ideal");
            idsaran.setText("Makan yang banyak dan bergizi");
    }//GEN-LAST:event_submithitungActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CekKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CekKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CekKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekKesehatan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CekKesehatan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Beratbadan;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggibadan;
    private javax.swing.JTextField beratideal;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JTextField idhasilanalisa;
    private javax.swing.JTextField idsaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jblaki;
    private javax.swing.JRadioButton jbperempuan;
    private javax.swing.JButton submithitung;
    private javax.swing.JButton submitkeluar;
    private javax.swing.JButton submitulangi;
    // End of variables declaration//GEN-END:variables
}
