/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lanjutan;

import javax.swing.JOptionPane;

/**
 *
 * @author Client
 */
public class converter extends javax.swing.JFrame {

    /**
     * Creates new form converter
     */
    public converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnKonversi = new javax.swing.JButton();
        btnTipeKonversi = new javax.swing.JButton();
        txtBiner = new javax.swing.JTextField();
        txtDesimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Masukkan Bilangan Biner");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 70, 170, 40);

        jLabel2.setText("Masukkan Bilangan Desimal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 170, 40);

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnKonversi);
        btnKonversi.setBounds(10, 200, 360, 40);

        btnTipeKonversi.setText("=>");
        btnTipeKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipeKonversiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTipeKonversi);
        btnTipeKonversi.setBounds(160, 130, 60, 40);
        getContentPane().add(txtBiner);
        txtBiner.setBounds(230, 130, 140, 40);
        getContentPane().add(txtDesimal);
        txtDesimal.setBounds(10, 130, 140, 40);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 140, 34, 15);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KONVERTER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 20, 250, 50);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 210, 300);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(210, 0, 190, 300);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTipeKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipeKonversiActionPerformed
        // TODO add your handling code here:
        if(btnTipeKonversi.getText().equals("=>")){
            btnTipeKonversi.setText("<=");
        } else {
            btnTipeKonversi.setText("=>");
        }
       
        if(btnTipeKonversi.getText().equals("=>")){
            txtBiner.setEnabled(false);
            txtBiner.setText("");
            txtDesimal.setEnabled(true);
        } else {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(false);
            txtDesimal.setText("");
        }
    
    }//GEN-LAST:event_btnTipeKonversiActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
        // TODO add your handling code here:
         try {   
           
            if(txtBiner.getText().isEmpty()){
                int desi = Integer.valueOf(txtDesimal.getText());
                // konversi ke biner
                String bin = Integer.toBinaryString(desi);
                txtBiner.setText(bin);
            } else {
                String biner = txtBiner.getText();
                // konversi ke desimal
                int des = Integer.parseInt(biner, 2);
                txtDesimal.setText(String.valueOf(des));
            }

           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input tidak valid: " + e.getMessage());
        } finally {
            txtBiner.setEnabled(true);
            txtDesimal.setEnabled(true);
        }

    }//GEN-LAST:event_btnKonversiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JButton btnTipeKonversi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBiner;
    private javax.swing.JTextField txtDesimal;
    // End of variables declaration//GEN-END:variables
}
