/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lanjutan;

import javax.swing.JOptionPane;

/**
 *
 * @author Client
 */
public class VolumeBangunRuang extends javax.swing.JFrame {

    /**
     * Creates new form VolumeBangunRuang
     */
    public VolumeBangunRuang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnVolumeKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnVolumeBola = new javax.swing.JButton();
        Jarijari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lebar = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(52, 12, 292, 28);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 20, 140, 40);

        Sisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SisiActionPerformed(evt);
            }
        });
        jPanel2.add(Sisi);
        Sisi.setBounds(10, 60, 110, 40);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(130, 70, 40, 20);

        btnVolumeKubus.setText("Volume");
        btnVolumeKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumeKubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolumeKubus);
        btnVolumeKubus.setBounds(10, 120, 70, 25);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari - jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 20, 140, 40);

        btnVolumeBola.setText("Volume");
        btnVolumeBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolumeBolaActionPerformed(evt);
            }
        });
        jPanel3.add(btnVolumeBola);
        btnVolumeBola.setBounds(20, 140, 70, 25);
        jPanel3.add(Jarijari);
        Jarijari.setBounds(10, 60, 140, 50);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(160, 70, 50, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Lebar :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 70, 110, 40);

        jLabel3.setText("Masukkan Tinggi :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 110, 40);

        jLabel4.setText("Masukkan Panjang :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 110, 40);

        Lebar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LebarActionPerformed(evt);
            }
        });
        jPanel1.add(Lebar);
        Lebar.setBounds(150, 70, 140, 40);

        Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinggiActionPerformed(evt);
            }
        });
        jPanel1.add(Tinggi);
        Tinggi.setBounds(150, 120, 140, 40);

        Panjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PanjangActionPerformed(evt);
            }
        });
        jPanel1.add(Panjang);
        Panjang.setBounds(150, 20, 140, 40);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 80, 40, 20);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 130, 40, 20);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 30, 40, 20);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        jPanel1.add(btnHitung);
        btnHitung.setBounds(210, 170, 64, 25);

        jTabbedPane1.addTab("Balok", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 400, 240);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void LebarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LebarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LebarActionPerformed

    private void TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinggiActionPerformed

    private void PanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PanjangActionPerformed

    private void SisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SisiActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(Panjang.getText());
        lebar = Integer.parseInt(Lebar.getText());
        tinggi = Integer.parseInt(Tinggi.getText());
        int hasil = panjang * lebar * tinggi;
        try{
            JOptionPane.showMessageDialog(null,"Volume Balok adalah : " + hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : " + e,"Gagal",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnVolumeKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumeKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try{
            JOptionPane.showMessageDialog(null,"Volume Kubus adalah : " + hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : " + e,"Gagal",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnVolumeKubusActionPerformed

    private void btnVolumeBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolumeBolaActionPerformed
        // TODO add your handling code here:
        double jari;
        jari = Integer.parseInt(Jarijari.getText());
        double hasil1=(double)(4/3*3.14*jari*jari);
        try{
            JOptionPane.showMessageDialog(null,"Volume Bola adalah : " + hasil1,"luas",JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error : " + e,"Gagal",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnVolumeBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolumeBangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolumeBangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jarijari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnVolumeBola;
    private javax.swing.JButton btnVolumeKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
